function loadcontent (IDcont)
{
    var content = {
        'Nike-dunk' : '<h3>Nike Dunk Brazil</h3> <br> <img style="margin-left: 10px; height: 500px; width: 800px; " src="images/sneakers/NikeDunk_Brazil.jpg" alt="Nike Dunk Image"><p>Nike brought back another popular Nike Dunk from the early 2000s with the release of the Nike Dunk Low Brazil (2020/2024), now available on StockX. The original Nike Dunk Low Brazil debuted in 2001 in both high and low cut variations. This Dunk Low Brazil features a yellow leather upper with green overlays and white detailing. A white midsole, green outsole, and yellow Nike branding on the heel complete the design. These sneakers released in May of 2020 and retailed for $100 USD. The Nike Dunk Low Brazil (2020/2024) restocked in February of 2024 and retailed for $115 USD.</p>',
        'Nike-air-force' : '<h3>Air Force Nocta White</h3> <br/> <img style="margin-left: 10px; height: 500px; width: 800px; " src="images/sneakers/AirForce_Nocta_White.jpg" alt="Nike Air Force Image"> <p>Previously dubbed "Certified Lover Boy", the new premium Drake-inspired AF1 is now known as the "Love You Forever." This sentiment is inspired by Drake’s favorite childhood book with subtle added details of the scripted "Love You Forever" on the midsole, in the same white color. Additional design elements include customized laces, NOCTA logo on left heel, and a new perforation pattern on toe box The special-edition Drake Nike Air Force 1 Low released December of 2022 fen Nike Air branding embroidered on the tongue are the final details. The Air Jordan 1 Retro High Hyper Royal debuted on 7 July 2018 and retailed at $160.or $160.</p>',
        'Jordan-1' : '<h3>Jordan 1 HyperRoyal</h3> <br> <img style="margin-left: 10px; height: 500px; width: 870px; " src="images/sneakers/Jordan1_HyperRoyal.jpg" alt="Nike Jordan 1"> <p>The Air Jordan 1 Retro High Hyper Royal features a white leather upper with fading blue suede overlays. The Swoosh and padded collar have neutral grey contrast accents, adding to the vintage-inspired aesthetic. A stitched Nike tongue tag and a Jordan Wings logo are branding elements on the lateral collar flap. The high-top shoe has encapsulated Nike Air units and is mounted on a regular AJ1 rubber cup sole. A white midsole, a Light Smoke Grey outsole, and a blue wov</p>',
        'Jordan-4' : '<h3>Jordan 4 Metallic Purple</h3> <br> <img style="margin-left: 10px; height: 500px; width: 800px; " src="images/sneakers/Jordan4MetallicPurple.jpg" alt="Nike Dunk Image"><p>Jordan Brand pays homage to one of its first colorway themes with the Jordan 4 Retro Metallic Purple, now available on StockX. In 1985, the Air Jordan 1 was the first in its lineage to receive the "Metallic" treatment. Four metallic colorways originally released - including red, orange, purple, and green. This release draws inspiration from the color blocking of the Jordan 1 Metallic Purple. This Jordan 4 features a white leather upper with white netted underlays and Metallic Purple detailing on the upper eyelets. A Metallic Purple Jumpman logo on the heel, white sole, and Metallic Purple Air bubble complete the design. These sneakers released in May of 2020 and retailed for $190 USD.</p>',
        'Adidas-campus' : '<h3>Adidas Campus Grey </h3> <br> <img style="margin-left: 10px; height: 500px; width: 800px; "src="images/sneakers/AdidasCampus_Grey.jpeg" alt="Nike Dunk Image"><p>The adidas Campus 00s Grey White comes in a grey three, footwear white, and off-white color scheme. The Grey White adidas Campus 00s has a grey and white upper with a subtle pattern. The shoes upper is constructed with suede for durability and style. The sneaker has a durable rubber outsole for stability and traction. The sneakers EVA wedge midsole provides comforting cushioning. The side perforations of the shoe provide ventilation and comfort. The shoe features the classic adidas 3-Stripes branding on the lateral sides. The sneaker has a "CAMPUS" inscription on one side. The shoes design is completed with the adidas Trefoil logo on the tongue and heel. The adidas Campus 00s Grey White was released at a retail price of $100 on March 1, 2023. </p>',
        'Adidas-samba' : '<h3>Adidas Samba Black / White </h3> <br> <img style="margin-left: 10px; height: 500px; width: 800px; " src="images/sneakers/AdidasSamba_BlackWhite.jpg" alt="Nike Dunk Image"> <p>The adidas Samba OG Cloud White Core Black (Womens) represents a contemporary take on a timeless style, emanating an aesthetic charm that goes beyond its original athletic purpose. Crafted from full-grain leather, the upper of the Cloud White Core Black adidas Samba OG (Womens) offers a sturdy and resilient construction. A gray suede, paired with a contrasting black heel tab, introduces an element of sophistication to the overall design. The iconic serrated 3-Stripes appear in black on both the lateral and medial sides, creating a visually striking contrast. Enhancing the shoes unique identity, a Bluebird tongue label and a foil logotype mark its distinctive DNA. Underneath, a brown gum rubber outsole ensures both traction and durability, underscoring the shoes practicality and style.​The standout characteristic of the adidas Samba OG Cloud White Core Black (Womens) lies in its signature T-toe design. This element pays homage to football pitches of the past, while embracing a forward-looking approach with its entirely vegan composition. The shoe debuted for $100 on December 1st, 2023.</p>'
    };

    var contentDiv = document.getElementById('Principal');

    contentDiv.innerHTML = content[IDcont];
}